### ISSUE TITLE
Pilot warnings

### ISSUE THREAD

**Issue by sbuchanYVR** [Helipaddy/report#4]
It is critical to call out approach and departure caution items.  They should not be buried in the landing details.  See my recent edits to a few PADs where I added them under Landing Instructions.   As they are both for Landing and Departure and need to be called out, a separate section would be very helpful

**Comment by paddywills** [comment]
This is done with the 360 pad survey.

We cannot have Helipaddy pilots inadvertently make a risk assessment on behalf of a site owner.

The landing box is a bit of a compromise - unclaimed (ie as yet unowned) sites can still have risk factors identified in a free format way. I totally agree with your wish to have all the risks identified though.

The challenge is getting site owner engagement.  But this will happen naturally once we bring PPR online (it's one of her reasons we are pushing for online PPR although I hear your comments about SMS)

**Comment by sbuchanYVR** [comment]
Can you review the PILOT CAUTIONS I added to the sites I augmented and the private site and let me know if, as stated, these work.   On Oct 5, 2023, at 1:25 AM, Paddy Wills ***@***.***> wrote:﻿
This is done with the 360 pad survey.
We cannot have Helipaddy pilots inadvertently make a risk assessment on behalf of a site owner.
The landing box is a bit of a compromise - unclaimed (ie as yet unowned) sites can still have risk factors identified in a free format way. I totally agree with your wish to have all the risks identified though.
The challenge is getting site owner engagement.  But this will happen naturally once we bring PPR online (it's one of her reasons we are pushing for online PPR although I hear your comments about SMS)

**Comment by paddywills** [comment]
I can't view private sites of pilots but I will look at the public sites

**Comment by sbuchanYVR** [comment]
I made Winslow Lake public.  then claimed it from ***@***.*** ***@***.***> .. you should now be able to see it.

**Comment by paddywills** [comment]
Closing but let me know if anything else on this subject

**Comment by sbuchanYVR** [comment]
Ok, understood. Will you be at the Cambridge event ?On Nov 18, 2023, at 8:02 AM, Paddy Wills ***@***.***> wrote:﻿
Closed #4 as completed.

**Comment by paddywills** [comment]
Yes

**Comment by sbuchanYVR** [comment]
Awesome.  Let’s catch up.  I will be at the 100 club dinner on the 5th, the owners event on the 6th and Jase has asked me to hang around for the public and press event on the 7th to chat with folks.  Lots of opportunity On Nov 18, 2023, at 12:33 PM, Paddy Wills ***@***.***> wrote:﻿
Yes
